In [8]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

In [9]:
dir_path = Path.cwd().parent

data_path = dir_path / "data" / "sales_data.csv"

In [10]:
database = pd.read_csv(data_path)

In [11]:
database.isnull().sum()

id_venda                0
data                    0
ano                     0
mês                     0
dia                     0
id_cliente              0
customer_segment        0
regiao                  0
estado                  0
produto_categoria       0
produto_nome            0
canal_venda             0
quantidade              0
preco_unitario          0
pct_desconto            0
gross_revenue           0
discount_value          0
net_revenue             0
cost                    0
profit                  0
margin_pct              0
Unnamed: 21          2000
Unnamed: 22          2000
Unnamed: 23          2000
Unnamed: 24          2000
Unnamed: 25          2000
Unnamed: 26          1988
Unnamed: 27          1988
dtype: int64

In [12]:
database.columns

Index(['id_venda', 'data', 'ano', 'mês', 'dia', 'id_cliente',
       'customer_segment', 'regiao', 'estado', 'produto_categoria',
       'produto_nome', 'canal_venda', 'quantidade', 'preco_unitario',
       'pct_desconto', 'gross_revenue', 'discount_value', 'net_revenue',
       'cost', 'profit', 'margin_pct', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27'],
      dtype='str')

In [13]:
database.drop(columns=['Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27'], inplace=True)

In [14]:
database.isnull().sum()

id_venda             0
data                 0
ano                  0
mês                  0
dia                  0
id_cliente           0
customer_segment     0
regiao               0
estado               0
produto_categoria    0
produto_nome         0
canal_venda          0
quantidade           0
preco_unitario       0
pct_desconto         0
gross_revenue        0
discount_value       0
net_revenue          0
cost                 0
profit               0
margin_pct           0
dtype: int64

In [15]:
database.head()

,id_venda,data,ano,mês,dia,id_cliente,customer_segment,regiao,estado,produto_categoria,...,canal_venda,quantidade,preco_unitario,pct_desconto,gross_revenue,discount_value,net_revenue,cost,profit,margin_pct
0,7,2023-01-21 00:00:00,2023,Janeiro,21,1383,Pequenas Empresas,Nordeste,PE,Móveis,...,E-commerce,14,"R$ 546,42",5%,"R$ 7.649,88","R$ 382,49","R$ 7.267,39","R$ 4.981,84","R$ 2.285,55","31,45"
1,15,2024-01-08 00:00:00,2024,Janeiro,8,1374,Pequenas Empresas,Centro-Oeste,GO,Escritório,...,E-commerce,5,"R$ 4.317,88",2%,"R$ 21.589,40","R$ 431,79","R$ 21.157,61","R$ 13.833,14","R$ 7.324,47","34,62"
2,24,2024-01-21 00:00:00,2024,Janeiro,21,1494,Corporativo,Nordeste,BA,Alimentos,...,E-commerce,2,"R$ 4.439,67",9%,"R$ 8.879,34","R$ 799,14","R$ 8.080,20","R$ 5.782,56","R$ 2.297,64","28,44"
3,30,2023-01-22 00:00:00,2023,Janeiro,22,1118,Corporativo,Sudeste,RJ,Móveis,...,Marketplace,8,"R$ 1.077,86",24%,"R$ 8.622,88","R$ 2.069,49","R$ 6.553,39","R$ 4.002,86","R$ 2.550,53","38,92"
4,48,2023-01-21 00:00:00,2023,Janeiro,21,1963,Pequenas Empresas,Sudeste,SP,Escritório,...,Marketplace,4,"R$ 2.386,87",8%,"R$ 9.547,48","R$ 763,80","R$ 8.783,68","R$ 5.376,95","R$ 3.406,73","38,78"

In [16]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           2000 non-null   int64
 1   data               2000 non-null   str
 2   ano                2000 non-null   int64
 3   mês                2000 non-null   str
 4   dia                2000 non-null   int64
 5   id_cliente         2000 non-null   int64
 6   customer_segment   2000 non-null   str
 7   regiao             2000 non-null   str
 8   estado             2000 non-null   str
 9   produto_categoria  2000 non-null   str
 10  produto_nome       2000 non-null   str
 11  canal_venda        2000 non-null   str
 12  quantidade         2000 non-null   int64
 13  preco_unitario     2000 non-null   str
 14  pct_desconto       2000 non-null   str
 15  gross_revenue      2000 non-null   str
 16  discount_value     2000 non-null   str
 17  net_revenue        2000 non-null   str
 18  cost               2000 non-null   str
 19  profit             2000 non-null   str
 20  margin_pct         2000 non-null   str
dtypes: int64(5), str(16)
memory usage: 328.3 KB

In [17]:
database['data'] = pd.to_datetime(database['data'])

In [18]:
database[['preco_unitario','pct_desconto','gross_revenue','discount_value','net_revenue','cost','profit','margin_pct']]

,preco_unitario,pct_desconto,gross_revenue,discount_value,net_revenue,cost,profit,margin_pct
0,"R$ 546,42",5%,"R$ 7.649,88","R$ 382,49","R$ 7.267,39","R$ 4.981,84","R$ 2.285,55","31,45"
1,"R$ 4.317,88",2%,"R$ 21.589,40","R$ 431,79","R$ 21.157,61","R$ 13.833,14","R$ 7.324,47","34,62"
2,"R$ 4.439,67",9%,"R$ 8.879,34","R$ 799,14","R$ 8.080,20","R$ 5.782,56","R$ 2.297,64","28,44"
3,"R$ 1.077,86",24%,"R$ 8.622,88","R$ 2.069,49","R$ 6.553,39","R$ 4.002,86","R$ 2.550,53","38,92"
4,"R$ 2.386,87",8%,"R$ 9.547,48","R$ 763,80","R$ 8.783,68","R$ 5.376,95","R$ 3.406,73","38,78"
...,...,...,...,...,...,...,...,...
1995,"R$ 4.598,60",12%,"R$ 45.986,00","R$ 5.518,32","R$ 40.467,68","R$ 24.061,99","R$ 16.405,69","40,54"
1996,"R$ 3.284,16",21%,"R$ 26.273,28","R$ 5.517,39","R$ 20.755,89","R$ 10.931,72","R$ 9.824,17","47,33"
1997,"R$ 1.518,61",1%,"R$ 6.074,44","R$ 60,74","R$ 6.013,70","R$ 3.604,55","R$ 2.409,15","40,06"
1998,"R$ 2.557,74",19%,"R$ 12.788,70","R$ 2.429,85","R$ 10.358,85","R$ 6.593,15","R$ 3.765,70","36,35"
1999,"R$ 292,45",4%,"R$ 1.462,25","R$ 58,49","R$ 1.403,76","R$ 1.054,53","R$ 349,23","24,88"

In [19]:
# Colunas que têm "R$" e caracteres especiais

colunas_moeda = ['preco_unitario', 'gross_revenue', 'discount_value', 'net_revenue', 'cost', 'profit']

for col in colunas_moeda:
    database[col] = database[col].str.replace('R$', '', regex=False).str.replace(',', '', regex=False).str.replace('.', '', regex=False).astype(float) / 100

# Colunas de porcentagem (tratadas individualmente por terem regras diferentes)

database['pct_desconto'] = database['pct_desconto'].str.replace('%', '', regex=False).str.replace(',', '', regex=False).str.replace('.', '', regex=False).astype(float) / 100
database['margin_pct'] = database['margin_pct'].str.replace(',', '', regex=False).astype(float) / 100

In [20]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           2000 non-null   int64
 1   data               2000 non-null   datetime64[us]
 2   ano                2000 non-null   int64
 3   mês                2000 non-null   str
 4   dia                2000 non-null   int64
 5   id_cliente         2000 non-null   int64
 6   customer_segment   2000 non-null   str
 7   regiao             2000 non-null   str
 8   estado             2000 non-null   str
 9   produto_categoria  2000 non-null   str
 10  produto_nome       2000 non-null   str
 11  canal_venda        2000 non-null   str
 12  quantidade         2000 non-null   int64
 13  preco_unitario     2000 non-null   float64
 14  pct_desconto       2000 non-null   float64
 15  gross_revenue      2000 non-null   float64
 16  discount_value     2000 non-null   float64
 17  net_revenue        2000 non-null   float64
 18  cost               2000 non-null   float64
 19  profit             2000 non-null   float64
 20  margin_pct         2000 non-null   float64
dtypes: datetime64[us](1), float64(8), int64(5), str(7)
memory usage: 328.3 KB

In [21]:
traducao_colunas = {
    'customer_segment': 'segmento_cliente',
    'gross_revenue': 'receita_bruta',
    'discount_value': 'valor_desconto',
    'net_revenue': 'receita_liquida',
    'cost': 'custo',
    'profit': 'lucro',
    'margin_pct': 'margem_pct'
}

database.rename(columns=traducao_colunas, inplace=True)

In [22]:
database.head()

,id_venda,data,ano,mês,dia,id_cliente,segmento_cliente,regiao,estado,produto_categoria,...,canal_venda,quantidade,preco_unitario,pct_desconto,receita_bruta,valor_desconto,receita_liquida,custo,lucro,margem_pct
0,7,2023-01-21,2023,Janeiro,21,1383,Pequenas Empresas,Nordeste,PE,Móveis,...,E-commerce,14,546.42,0.05,7649.88,382.49,7267.39,4981.84,2285.55,31.45
1,15,2024-01-08,2024,Janeiro,8,1374,Pequenas Empresas,Centro-Oeste,GO,Escritório,...,E-commerce,5,4317.88,0.02,21589.40,431.79,21157.61,13833.14,7324.47,34.62
2,24,2024-01-21,2024,Janeiro,21,1494,Corporativo,Nordeste,BA,Alimentos,...,E-commerce,2,4439.67,0.09,8879.34,799.14,8080.20,5782.56,2297.64,28.44
3,30,2023-01-22,2023,Janeiro,22,1118,Corporativo,Sudeste,RJ,Móveis,...,Marketplace,8,1077.86,0.24,8622.88,2069.49,6553.39,4002.86,2550.53,38.92
4,48,2023-01-21,2023,Janeiro,21,1963,Pequenas Empresas,Sudeste,SP,Escritório,...,Marketplace,4,2386.87,0.08,9547.48,763.80,8783.68,5376.95,3406.73,38.78

# Análise descritiva

1 - Quanto vendemos?

2 - Quanto lucramos?

3 - Onde vendemos?

4 - O que vendemos?

5 - Para quem vendemos?

6 - Por qual canal?

# Análise diagnóstica

7 - Quais regiões possuem maior margem?

8 - Quais produtos geram maior lucro?

9 - Quais segmentos possuem maior potencial?

10 - Quais canais possuem melhor rentabilidade?

11 - Onde os descontos estão reduzindo margem?

12 - Existe sazonalidade?

# Análise estratégica

13 - Onde devemos concentrar vendas?

14 - Quais segmentos devemos priorizar?

15 - Quais produtos devemos promover?

16 - Quais canais merecem maior investimento?

17 - Onde devemos controlar descontos?