In [142]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns
import locale

# 📊 Análise de Vendas

## Contexto

Este projeto apresenta uma análise exploratória de uma base fictícia de vendas, composta por **10.000 registros entre 2021 e 2025**.

Os dados contemplam informações sobre **clientes, segmentos, regiões, estados, produtos, canais de venda, quantidade, descontos e indicadores financeiros**, permitindo avaliar a performance comercial sob diferentes perspectivas.

## Objetivo

Identificar **padrões, tendências e oportunidades de negócio** a partir da análise de:

* 📈 Evolução das vendas e da receita ao longo dos anos;
* 👥 Desempenho dos segmentos de clientes;
* 🌎 Performance por região e estado;
* 📦 Desempenho e potencial dos produtos;
* 🛒 Comparação entre canais de venda;
* 📅 Sazonalidade e comportamento mensal;
* 💰 Receita, custos, lucro e margem.

A análise busca ir além da descrição dos dados, procurando entender **quais fatores estão relacionados à performance comercial e onde existem oportunidades de melhoria ou crescimento**.

## Pergunta central

> **Quais segmentos, produtos, regiões e períodos apresentam maior potencial de geração de receita e lucro entre 2021 e 2025?**

## Etapas da análise

**Conhecimento dos dados → Qualidade e tratamento → Análise exploratória → KPIs → Segmentação → Tendências e sazonalidade → Insights → Recomendações**

## 1. Preparação dos dados

In [143]:
dir_path = Path.cwd().parent

data_path = dir_path / "data" / "sales_data.csv"

In [144]:
database = pd.read_csv(data_path)

In [145]:
database.isnull().sum()

id_venda                 0
data                     0
ano                      0
mês                      0
dia                      0
id_cliente               0
customer_segment         0
regiao                   0
estado                   0
produto_categoria        0
produto_nome             0
canal_venda              0
quantidade               0
preco_unitario           0
pct_desconto             0
gross_revenue            0
discount_value           0
net_revenue              0
cost                     0
profit                   0
margin_pct               0
Unnamed: 21          10000
Unnamed: 22          10000
Unnamed: 23          10000
Unnamed: 24          10000
Unnamed: 25          10000
Unnamed: 26           9988
Unnamed: 27           9988
dtype: int64

In [146]:
database.columns

Index(['id_venda', 'data', 'ano', 'mês', 'dia', 'id_cliente',
       'customer_segment', 'regiao', 'estado', 'produto_categoria',
       'produto_nome', 'canal_venda', 'quantidade', 'preco_unitario',
       'pct_desconto', 'gross_revenue', 'discount_value', 'net_revenue',
       'cost', 'profit', 'margin_pct', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27'],
      dtype='str')

In [147]:
database.drop(columns=['Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27'], inplace=True)

In [148]:
database.isnull().sum()

id_venda             0
data                 0
ano                  0
mês                  0
dia                  0
id_cliente           0
customer_segment     0
regiao               0
estado               0
produto_categoria    0
produto_nome         0
canal_venda          0
quantidade           0
preco_unitario       0
pct_desconto         0
gross_revenue        0
discount_value       0
net_revenue          0
cost                 0
profit               0
margin_pct           0
dtype: int64

In [149]:
database.head()

,id_venda,data,ano,mês,dia,id_cliente,customer_segment,regiao,estado,produto_categoria,...,canal_venda,quantidade,preco_unitario,pct_desconto,gross_revenue,discount_value,net_revenue,cost,profit,margin_pct
0,1,2023-01-01 00:00:00,2023,Janeiro,1,1129,Corporativo,Nordeste,BA,Eletrônicos,...,E-commerce,23,"R$ 2.750,90",7%,"R$ 63.270,67","R$ 4.338,66","R$ 58.932,02","R$ 41.648,12","R$ 17.283,90","29,33"
1,2,2023-01-01 00:00:00,2023,Janeiro,1,1963,Pequenas Empresas,Sudeste,SP,Eletrônicos,...,E-commerce,9,"R$ 1.054,99",5%,"R$ 9.494,89","R$ 431,81","R$ 9.063,08","R$ 5.244,14","R$ 3.818,94","42,14"
2,3,2023-01-02 00:00:00,2023,Janeiro,2,1385,Pequenas Empresas,Sul,SC,Eletrônicos,...,E-commerce,8,"R$ 676,88",12%,"R$ 5.415,04","R$ 635,28","R$ 4.779,76","R$ 2.827,43","R$ 1.952,33","40,85"
3,4,2023-01-02 00:00:00,2023,Janeiro,2,1304,Pequenas Empresas,Nordeste,PE,Eletrônicos,...,Loja Física,3,"R$ 783,48",4%,"R$ 2.350,45","R$ 104,62","R$ 2.245,83","R$ 1.602,67","R$ 643,17","28,64"
4,5,2023-01-02 00:00:00,2023,Janeiro,2,1808,Corporativo,Centro-Oeste,GO,Eletrônicos,...,E-commerce,36,"R$ 2.959,06",3%,"R$ 106.526,25","R$ 3.114,00","R$ 103.412,25","R$ 67.202,04","R$ 36.210,21","35,02"

In [150]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           10000 non-null  int64
 1   data               10000 non-null  str
 2   ano                10000 non-null  int64
 3   mês                10000 non-null  str
 4   dia                10000 non-null  int64
 5   id_cliente         10000 non-null  int64
 6   customer_segment   10000 non-null  str
 7   regiao             10000 non-null  str
 8   estado             10000 non-null  str
 9   produto_categoria  10000 non-null  str
 10  produto_nome       10000 non-null  str
 11  canal_venda        10000 non-null  str
 12  quantidade         10000 non-null  int64
 13  preco_unitario     10000 non-null  str
 14  pct_desconto       10000 non-null  str
 15  gross_revenue      10000 non-null  str
 16  discount_value     10000 non-null  str
 17  net_revenue        10000 non-null  str
 18  cost               10000 non-null  str
 19  profit             10000 non-null  str
 20  margin_pct         10000 non-null  str
dtypes: int64(5), str(16)
memory usage: 1.6 MB

In [151]:
database['data'] = pd.to_datetime(database['data'])

In [152]:
meses = {
    'Janeiro': 1,
    'Fevereiro': 2,
    'Março': 3,
    'Abril': 4,
    'Maio': 5,
    'Junho': 6,
    'Julho': 7,
    'Agosto': 8,
    'Setembro': 9,
    'Outubro': 10,
    'Novembro': 11,
    'Dezembro': 12
}

database['mes_num'] = database['mês'].map(meses)

## 2. Qualidade dos dados

In [153]:
database[['preco_unitario','pct_desconto','gross_revenue','discount_value','net_revenue','cost','profit','margin_pct']]

,preco_unitario,pct_desconto,gross_revenue,discount_value,net_revenue,cost,profit,margin_pct
0,"R$ 2.750,90",7%,"R$ 63.270,67","R$ 4.338,66","R$ 58.932,02","R$ 41.648,12","R$ 17.283,90","29,33"
1,"R$ 1.054,99",5%,"R$ 9.494,89","R$ 431,81","R$ 9.063,08","R$ 5.244,14","R$ 3.818,94","42,14"
2,"R$ 676,88",12%,"R$ 5.415,04","R$ 635,28","R$ 4.779,76","R$ 2.827,43","R$ 1.952,33","40,85"
3,"R$ 783,48",4%,"R$ 2.350,45","R$ 104,62","R$ 2.245,83","R$ 1.602,67","R$ 643,17","28,64"
4,"R$ 2.959,06",3%,"R$ 106.526,25","R$ 3.114,00","R$ 103.412,25","R$ 67.202,04","R$ 36.210,21","35,02"
...,...,...,...,...,...,...,...,...
9995,"R$ 920,98",9%,"R$ 11.972,79","R$ 1.039,07","R$ 10.933,72","R$ 6.151,19","R$ 4.782,53","43,74"
9996,"R$ 980,99",11%,"R$ 8.828,87","R$ 940,82","R$ 7.888,05","R$ 4.454,98","R$ 3.433,06","43,52"
9997,"R$ 775,07",9%,"R$ 5.425,47","R$ 462,96","R$ 4.962,51","R$ 2.779,44","R$ 2.183,06","43,99"
9998,"R$ 821,45",10%,"R$ 5.750,17","R$ 555,20","R$ 5.194,97","R$ 3.328,97","R$ 1.866,00","35,92"
9999,"R$ 827,93",10%,"R$ 7.451,34","R$ 743,76","R$ 6.707,59","R$ 4.559,26","R$ 2.148,32","32,03"

In [154]:
# Colunas que têm "R$" e caracteres especiais

colunas_moeda = ['preco_unitario', 'gross_revenue', 'discount_value', 'net_revenue', 'cost', 'profit']

for col in colunas_moeda:
    database[col] = database[col].str.replace('R$', '', regex=False).str.replace(',', '', regex=False).str.replace('.', '', regex=False).astype(float) / 100

# Colunas de porcentagem (tratadas individualmente por terem regras diferentes)

database['pct_desconto'] = database['pct_desconto'].str.replace('%', '', regex=False).str.replace(',', '', regex=False).str.replace('.', '', regex=False).astype(float) / 100
database['margin_pct'] = database['margin_pct'].str.replace(',', '', regex=False).astype(float) / 100

In [155]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           10000 non-null  int64
 1   data               10000 non-null  datetime64[us]
 2   ano                10000 non-null  int64
 3   mês                10000 non-null  str
 4   dia                10000 non-null  int64
 5   id_cliente         10000 non-null  int64
 6   customer_segment   10000 non-null  str
 7   regiao             10000 non-null  str
 8   estado             10000 non-null  str
 9   produto_categoria  10000 non-null  str
 10  produto_nome       10000 non-null  str
 11  canal_venda        10000 non-null  str
 12  quantidade         10000 non-null  int64
 13  preco_unitario     10000 non-null  float64
 14  pct_desconto       10000 non-null  float64
 15  gross_revenue      10000 non-null  float64
 16  discount_value     10000 non-null  float64
 17  net_revenue        10000 non-null  float64
 18  cost               10000 non-null  float64
 19  profit             10000 non-null  float64
 20  margin_pct         10000 non-null  float64
 21  mes_num            10000 non-null  int64
dtypes: datetime64[us](1), float64(8), int64(6), str(7)
memory usage: 1.7 MB

In [156]:
traducao_colunas = {
    'customer_segment': 'segmento_cliente',
    'gross_revenue': 'receita_bruta',
    'discount_value': 'valor_desconto',
    'net_revenue': 'receita_liquida',
    'cost': 'custo',
    'profit': 'lucro',
    'margin_pct': 'margem_pct'
}

database.rename(columns=traducao_colunas, inplace=True)

In [157]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           10000 non-null  int64
 1   data               10000 non-null  datetime64[us]
 2   ano                10000 non-null  int64
 3   mês                10000 non-null  str
 4   dia                10000 non-null  int64
 5   id_cliente         10000 non-null  int64
 6   segmento_cliente   10000 non-null  str
 7   regiao             10000 non-null  str
 8   estado             10000 non-null  str
 9   produto_categoria  10000 non-null  str
 10  produto_nome       10000 non-null  str
 11  canal_venda        10000 non-null  str
 12  quantidade         10000 non-null  int64
 13  preco_unitario     10000 non-null  float64
 14  pct_desconto       10000 non-null  float64
 15  receita_bruta      10000 non-null  float64
 16  valor_desconto     10000 non-null  float64
 17  receita_liquida    10000 non-null  float64
 18  custo              10000 non-null  float64
 19  lucro              10000 non-null  float64
 20  margem_pct         10000 non-null  float64
 21  mes_num            10000 non-null  int64
dtypes: datetime64[us](1), float64(8), int64(6), str(7)
memory usage: 1.7 MB

## 3. Análise descritiva

### Vendas e faturamento

1. **Quanto vendemos?** — Qual o total de vendas, quantidade vendida e faturamento bruto e líquido?
2. **Como as vendas estão distribuídas ao longo do período?** — Qual o volume e faturamento por ano e mês?
3. **Qual é o ticket médio das vendas?** — Como ele varia ao longo do período?

### Geografia

4. **Onde vendemos?** — Como as vendas estão distribuídas por região e estado?
5. **Quais regiões e estados concentram maior faturamento e volume de vendas?**

### Produtos

6. **O que vendemos?** — Quais categorias e produtos possuem maior participação nas vendas?
7. **Quais produtos apresentam maior quantidade vendida e maior faturamento?**

### Clientes

8. **Para quem vendemos?** — Como as vendas estão distribuídas entre os segmentos de clientes?
9. **Qual é o ticket médio e o volume de vendas de cada segmento?**

### Canais

10. **Por qual canal vendemos?** — Como as vendas, faturamento e quantidade estão distribuídos entre E-commerce e Loja Física?
11. **Existe diferença de comportamento entre segmentos e canais de venda?**

## 4. Análise diagnóstica

### Performance comercial

12. **Quais fatores estão associados às diferenças de performance entre regiões?**
13. **Quais produtos contribuem mais para o faturamento e quais possuem baixa participação?**
14. **Quais segmentos apresentam maior volume, faturamento e ticket médio?**
15. **Quais canais apresentam melhor desempenho comercial?**

### Descontos

16. **Onde os descontos estão mais concentrados?**
17. **Existe relação entre percentual de desconto, faturamento e margem?**
18. **Quais regiões, produtos, segmentos ou canais concedem maiores descontos?**
19. **Em quais situações o desconto parece comprometer a rentabilidade?**

### Sazonalidade

20. **Existe sazonalidade nas vendas?**
21. **Quais meses apresentam maior e menor volume, faturamento e lucro?**
22. **A sazonalidade se comporta de maneira diferente entre regiões, produtos e segmentos?**

## 5. Análise de rentabilidade

23. **Quanto lucramos?** — Qual o lucro total e a margem média?
24. **Quais regiões possuem maior lucro e margem?**
25. **Quais produtos geram maior lucro?**
26. **Quais produtos apresentam maior margem percentual?**
27. **Existem produtos com alto faturamento, mas baixa margem?**
28. **Quais segmentos apresentam maior rentabilidade?**
29. **Quais canais possuem melhor margem e lucro?**
30. **Quais combinações de produto, segmento, região e canal são mais rentáveis?**
31. **Onde existe maior diferença entre faturamento e geração de lucro?**

## 6. Análise de segmentos

32. **Qual segmento apresenta maior potencial de faturamento?**
33. **Qual segmento apresenta maior potencial de lucro?**
34. **Qual segmento apresenta melhor margem?**
35. **Como quantidade, ticket médio, desconto e margem diferem entre os segmentos?**
36. **Quais produtos possuem maior demanda em cada segmento?**
37. **Quais regiões são mais relevantes para cada segmento?**
38. **Existe algum segmento com alto volume, mas baixa rentabilidade?**
39. **Como o desempenho dos segmentos evoluiu entre 2021 e 2025?**

## 7. Análise temporal

40. **Como vendas, faturamento, lucro e margem evoluíram entre 2021 e 2025?**
41. **Qual foi o crescimento anual do faturamento?**
42. **Quais anos apresentaram maior e menor performance?**
43. **Quais produtos apresentaram maior crescimento ao longo dos anos?**
44. **Quais segmentos ganharam ou perderam participação no período?**
45. **Quais regiões apresentaram maior crescimento?**
46. **A margem está aumentando ou diminuindo ao longo do tempo?**
47. **Os padrões sazonais se repetem nos cinco anos?**
48. **Existem mudanças relevantes no comportamento dos canais ao longo do período?**

## 8. Insights e recomendações

49. **Onde devemos concentrar esforços comerciais?** — Quais regiões apresentam melhor combinação de crescimento, faturamento e rentabilidade?
50. **Quais segmentos devemos priorizar?** — Onde existe maior potencial de receita e lucro?
51. **Quais produtos devemos promover?** — Quais apresentam melhor combinação de demanda, crescimento e margem?
52. **Quais produtos devem ser monitorados?** — Existem produtos com alto volume, mas baixa rentabilidade?
53. **Quais canais merecem maior investimento?** — Qual apresenta maior potencial de crescimento e rentabilidade?
54. **Onde devemos controlar descontos?** — Quais combinações de produto, segmento, região e canal apresentam maior impacto negativo na margem?
55. **Quais períodos exigem maior preparação comercial?** — Quando concentrar estoque, campanhas ou esforços de vendas?
56. **Quais oportunidades de crescimento estão subexploradas?**
57. **Quais são os principais riscos identificados na performance comercial?**
58. **Quais ações podem aumentar receita sem comprometer a margem?**