In [341]:
import pandas as pd
from pathlib import Path
import matplotlib.pyplot as plt
import seaborn as sns

In [342]:
dir_path = Path.cwd().parent

data_path = dir_path / "data" / "sales_data.csv"

In [343]:
database = pd.read_csv(data_path)

In [344]:
database.isnull().sum()

id_venda                0
data                    0
ano                     0
mês                     0
dia                     0
id_cliente              0
customer_segment        0
regiao                  0
estado                  0
produto_categoria       0
produto_nome            0
canal_venda             0
quantidade              0
preco_unitario          0
pct_desconto            0
gross_revenue           0
discount_value          0
net_revenue             0
cost                    0
profit                  0
margin_pct              0
Unnamed: 21          2000
Unnamed: 22          2000
Unnamed: 23          2000
Unnamed: 24          2000
Unnamed: 25          2000
Unnamed: 26          1988
Unnamed: 27          1988
dtype: int64

In [345]:
database.columns

Index(['id_venda', 'data', 'ano', 'mês', 'dia', 'id_cliente',
       'customer_segment', 'regiao', 'estado', 'produto_categoria',
       'produto_nome', 'canal_venda', 'quantidade', 'preco_unitario',
       'pct_desconto', 'gross_revenue', 'discount_value', 'net_revenue',
       'cost', 'profit', 'margin_pct', 'Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27'],
      dtype='str')

In [346]:
database.drop(columns=['Unnamed: 21', 'Unnamed: 22',
       'Unnamed: 23', 'Unnamed: 24', 'Unnamed: 25', 'Unnamed: 26',
       'Unnamed: 27'], inplace=True)

In [347]:
database.isnull().sum()

id_venda             0
data                 0
ano                  0
mês                  0
dia                  0
id_cliente           0
customer_segment     0
regiao               0
estado               0
produto_categoria    0
produto_nome         0
canal_venda          0
quantidade           0
preco_unitario       0
pct_desconto         0
gross_revenue        0
discount_value       0
net_revenue          0
cost                 0
profit               0
margin_pct           0
dtype: int64

In [348]:
database.head()

,id_venda,data,ano,mês,dia,id_cliente,customer_segment,regiao,estado,produto_categoria,...,canal_venda,quantidade,preco_unitario,pct_desconto,gross_revenue,discount_value,net_revenue,cost,profit,margin_pct
0,1,2023-01-01 00:00:00,2023,Janeiro,1,1129,Corporativo,Nordeste,BA,Eletrônicos,...,E-commerce,23,"R$ 2.750,90",7%,"R$ 63.270,67","R$ 4.338,66","R$ 58.932,02","R$ 41.648,12","R$ 17.283,90","29,33"
1,2,2023-01-01 00:00:00,2023,Janeiro,1,1963,Pequenas Empresas,Sudeste,SP,Eletrônicos,...,E-commerce,9,"R$ 1.054,99",5%,"R$ 9.494,89","R$ 431,81","R$ 9.063,08","R$ 5.244,14","R$ 3.818,94","42,14"
2,3,2023-01-02 00:00:00,2023,Janeiro,2,1385,Pequenas Empresas,Sul,SC,Eletrônicos,...,E-commerce,8,"R$ 676,88",12%,"R$ 5.415,04","R$ 635,28","R$ 4.779,76","R$ 2.827,43","R$ 1.952,33","40,85"
3,4,2023-01-02 00:00:00,2023,Janeiro,2,1304,Pequenas Empresas,Nordeste,PE,Eletrônicos,...,Loja Física,3,"R$ 783,48",4%,"R$ 2.350,45","R$ 104,62","R$ 2.245,83","R$ 1.602,67","R$ 643,17","28,64"
4,5,2023-01-02 00:00:00,2023,Janeiro,2,1808,Corporativo,Centro-Oeste,GO,Eletrônicos,...,E-commerce,36,"R$ 2.959,06",3%,"R$ 106.526,25","R$ 3.114,00","R$ 103.412,25","R$ 67.202,04","R$ 36.210,21","35,02"

In [349]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           2000 non-null   int64
 1   data               2000 non-null   str
 2   ano                2000 non-null   int64
 3   mês                2000 non-null   str
 4   dia                2000 non-null   int64
 5   id_cliente         2000 non-null   int64
 6   customer_segment   2000 non-null   str
 7   regiao             2000 non-null   str
 8   estado             2000 non-null   str
 9   produto_categoria  2000 non-null   str
 10  produto_nome       2000 non-null   str
 11  canal_venda        2000 non-null   str
 12  quantidade         2000 non-null   int64
 13  preco_unitario     2000 non-null   str
 14  pct_desconto       2000 non-null   str
 15  gross_revenue      2000 non-null   str
 16  discount_value     2000 non-null   str
 17  net_revenue        2000 non-null   str
 18  cost               2000 non-null   str
 19  profit             2000 non-null   str
 20  margin_pct         2000 non-null   str
dtypes: int64(5), str(16)
memory usage: 328.3 KB

In [350]:
database['data'] = pd.to_datetime(database['data'])

In [351]:
meses = {
    'Janeiro': 1,
    'Fevereiro': 2,
    'Março': 3,
    'Abril': 4,
    'Maio': 5,
    'Junho': 6,
    'Julho': 7,
    'Agosto': 8,
    'Setembro': 9,
    'Outubro': 10,
    'Novembro': 11,
    'Dezembro': 12
}

database['mes_num'] = database['mês'].map(meses)

In [352]:
database[['preco_unitario','pct_desconto','gross_revenue','discount_value','net_revenue','cost','profit','margin_pct']]

,preco_unitario,pct_desconto,gross_revenue,discount_value,net_revenue,cost,profit,margin_pct
0,"R$ 2.750,90",7%,"R$ 63.270,67","R$ 4.338,66","R$ 58.932,02","R$ 41.648,12","R$ 17.283,90","29,33"
1,"R$ 1.054,99",5%,"R$ 9.494,89","R$ 431,81","R$ 9.063,08","R$ 5.244,14","R$ 3.818,94","42,14"
2,"R$ 676,88",12%,"R$ 5.415,04","R$ 635,28","R$ 4.779,76","R$ 2.827,43","R$ 1.952,33","40,85"
3,"R$ 783,48",4%,"R$ 2.350,45","R$ 104,62","R$ 2.245,83","R$ 1.602,67","R$ 643,17","28,64"
4,"R$ 2.959,06",3%,"R$ 106.526,25","R$ 3.114,00","R$ 103.412,25","R$ 67.202,04","R$ 36.210,21","35,02"
...,...,...,...,...,...,...,...,...
1995,"R$ 2.984,01",4%,"R$ 53.712,10","R$ 2.239,60","R$ 51.472,50","R$ 34.000,75","R$ 17.471,75","33,94"
1996,"R$ 2.079,35",6%,"R$ 56.142,45","R$ 3.321,86","R$ 52.820,59","R$ 35.106,72","R$ 17.713,87","33,54"
1997,"R$ 1.028,88",2%,"R$ 3.086,64","R$ 72,14","R$ 3.014,50","R$ 1.878,08","R$ 1.136,42","37,70"
1998,"R$ 156,07",8%,"R$ 312,13","R$ 26,15","R$ 285,98","R$ 172,11","R$ 113,86","39,82"
1999,"R$ 384,63",10%,"R$ 769,25","R$ 76,43","R$ 692,83","R$ 395,10","R$ 297,72","42,97"

In [353]:
# Colunas que têm "R$" e caracteres especiais

colunas_moeda = ['preco_unitario', 'gross_revenue', 'discount_value', 'net_revenue', 'cost', 'profit']

for col in colunas_moeda:
    database[col] = database[col].str.replace('R$', '', regex=False).str.replace(',', '', regex=False).str.replace('.', '', regex=False).astype(float) / 100

# Colunas de porcentagem (tratadas individualmente por terem regras diferentes)

database['pct_desconto'] = database['pct_desconto'].str.replace('%', '', regex=False).str.replace(',', '', regex=False).str.replace('.', '', regex=False).astype(float) / 100
database['margin_pct'] = database['margin_pct'].str.replace(',', '', regex=False).astype(float) / 100

In [354]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           2000 non-null   int64
 1   data               2000 non-null   datetime64[us]
 2   ano                2000 non-null   int64
 3   mês                2000 non-null   str
 4   dia                2000 non-null   int64
 5   id_cliente         2000 non-null   int64
 6   customer_segment   2000 non-null   str
 7   regiao             2000 non-null   str
 8   estado             2000 non-null   str
 9   produto_categoria  2000 non-null   str
 10  produto_nome       2000 non-null   str
 11  canal_venda        2000 non-null   str
 12  quantidade         2000 non-null   int64
 13  preco_unitario     2000 non-null   float64
 14  pct_desconto       2000 non-null   float64
 15  gross_revenue      2000 non-null   float64
 16  discount_value     2000 non-null   float64
 17  net_revenue        2000 non-null   float64
 18  cost               2000 non-null   float64
 19  profit             2000 non-null   float64
 20  margin_pct         2000 non-null   float64
 21  mes_num            2000 non-null   int64
dtypes: datetime64[us](1), float64(8), int64(6), str(7)
memory usage: 343.9 KB

In [355]:
traducao_colunas = {
    'customer_segment': 'segmento_cliente',
    'gross_revenue': 'receita_bruta',
    'discount_value': 'valor_desconto',
    'net_revenue': 'receita_liquida',
    'cost': 'custo',
    'profit': 'lucro',
    'margin_pct': 'margem_pct'
}

database.rename(columns=traducao_colunas, inplace=True)

In [356]:
database.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           2000 non-null   int64
 1   data               2000 non-null   datetime64[us]
 2   ano                2000 non-null   int64
 3   mês                2000 non-null   str
 4   dia                2000 non-null   int64
 5   id_cliente         2000 non-null   int64
 6   segmento_cliente   2000 non-null   str
 7   regiao             2000 non-null   str
 8   estado             2000 non-null   str
 9   produto_categoria  2000 non-null   str
 10  produto_nome       2000 non-null   str
 11  canal_venda        2000 non-null   str
 12  quantidade         2000 non-null   int64
 13  preco_unitario     2000 non-null   float64
 14  pct_desconto       2000 non-null   float64
 15  receita_bruta      2000 non-null   float64
 16  valor_desconto     2000 non-null   float64
 17  receita_liquida    2000 non-null   float64
 18  custo              2000 non-null   float64
 19  lucro              2000 non-null   float64
 20  margem_pct         2000 non-null   float64
 21  mes_num            2000 non-null   int64
dtypes: datetime64[us](1), float64(8), int64(6), str(7)
memory usage: 343.9 KB

# Análise descritiva

1 - Quanto vendemos (total e por mês)?

2 - Quanto lucramos (total e por mês)?

3 - Onde vendemos?

4 - O que vendemos?

5 - Para quem vendemos?

6 - Por qual canal?

In [357]:
#1 - Faturamento total

import locale

faturamento_total = database['receita_liquida'].sum()

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
print(f'{locale.currency(faturamento_total, grouping=True)}')

R$ 39.424.945,46

In [358]:
# 1.1 - Faturamento por mês

faturamento_mes = database.groupby(['ano','mês','mes_num'])['receita_liquida'].sum().reset_index().sort_values(by=['ano','mes_num'])

faturamento_mes['receita_liquida'] = faturamento_mes['receita_liquida'].apply(lambda x: locale.currency(x, grouping=True))

faturamento_mes

     ano        mês  mes_num  receita_liquida
4   2023    Janeiro        1  R$ 1.224.675,47
3   2023  Fevereiro        2    R$ 736.253,33
8   2023      Março        3    R$ 785.135,64
0   2023      Abril        4    R$ 718.535,43
7   2023       Maio        5  R$ 1.897.931,40
6   2023      Junho        6  R$ 1.672.703,17
5   2023      Julho        7  R$ 1.060.792,90
1   2023     Agosto        8  R$ 2.548.047,76
11  2023   Setembro        9  R$ 1.754.673,41
10  2023    Outubro       10  R$ 1.939.629,85
9   2023   Novembro       11  R$ 2.997.643,11
2   2023   Dezembro       12  R$ 2.519.635,74
16  2024    Janeiro        1  R$ 1.023.319,79
15  2024  Fevereiro        2    R$ 336.997,49
20  2024      Março        3  R$ 1.078.433,61
12  2024      Abril        4  R$ 1.424.721,81
19  2024       Maio        5  R$ 1.087.669,19
18  2024      Junho        6    R$ 866.349,71
17  2024      Julho        7  R$ 1.522.419,00
13  2024     Agosto        8  R$ 1.320.041,24
23  2024   Setembro        9  R$ 1.566.070,58
22  2024    Outubro       10  R$ 2.018.506,47
21  2024   Novembro       11  R$ 4.760.274,60
14  2024   Dezembro       12  R$ 2.564.484,76

In [359]:
# 2 - Lucro total

import locale

lucro_total = database['lucro'].sum()

locale.setlocale(locale.LC_ALL, 'pt_BR.UTF-8')
print(f'{locale.currency(lucro_total, grouping=True)}')

R$ 14.783.575,13

In [360]:
# 2.1 - Lucro por mês

lucro_mes = database.groupby(['ano','mês','mes_num'])['lucro'].sum().reset_index().sort_values(by=['ano','mes_num'])

lucro_mes['lucro'] = lucro_mes['lucro'].apply(lambda x: locale.currency(x, grouping=True))

lucro_mes

     ano        mês  mes_num            lucro
4   2023    Janeiro        1    R$ 450.389,96
3   2023  Fevereiro        2    R$ 253.545,04
8   2023      Março        3    R$ 306.372,89
0   2023      Abril        4    R$ 275.236,89
7   2023       Maio        5    R$ 727.146,73
6   2023      Junho        6    R$ 642.920,34
5   2023      Julho        7    R$ 383.506,37
1   2023     Agosto        8    R$ 949.795,83
11  2023   Setembro        9    R$ 665.517,65
10  2023    Outubro       10    R$ 704.435,37
9   2023   Novembro       11  R$ 1.097.652,05
2   2023   Dezembro       12    R$ 955.368,27
16  2024    Janeiro        1    R$ 407.769,80
15  2024  Fevereiro        2    R$ 126.488,10
20  2024      Março        3    R$ 394.207,29
12  2024      Abril        4    R$ 575.910,34
19  2024       Maio        5    R$ 390.764,38
18  2024      Junho        6    R$ 316.348,40
17  2024      Julho        7    R$ 578.143,38
13  2024     Agosto        8    R$ 518.415,56
23  2024   Setembro        9    R$ 589.422,65
22  2024    Outubro       10    R$ 799.420,30
21  2024   Novembro       11  R$ 1.749.713,07
14  2024   Dezembro       12    R$ 925.084,47

In [361]:
# 3 - Faturamento por região

faturamento_total_regiao = database.groupby(['regiao'])['receita_liquida'].sum().reset_index().sort_values(by=['regiao'])

faturamento_total_regiao['receita_liquida'] = faturamento_total_regiao['receita_liquida'].apply(lambda x: locale.currency(x, grouping=True))

faturamento_total_regiao

         regiao   receita_liquida
0  Centro-Oeste   R$ 4.783.800,93
1      Nordeste  R$ 10.956.992,15
2       Sudeste  R$ 12.126.290,30
3           Sul  R$ 11.557.862,08

In [362]:
# 3.1 - Faturamento por região e ano

faturamento_regiao = database.groupby(['ano','regiao'])['receita_liquida'].sum().reset_index().sort_values(by=['ano','regiao'])

faturamento_regiao['receita_liquida'] = faturamento_regiao['receita_liquida'].apply(lambda x: locale.currency(x, grouping=True))

faturamento_regiao

    ano        regiao  receita_liquida
0  2023  Centro-Oeste  R$ 2.199.573,82
1  2023      Nordeste  R$ 5.772.767,30
2  2023       Sudeste  R$ 6.204.153,92
3  2023           Sul  R$ 5.679.162,17
4  2024  Centro-Oeste  R$ 2.584.227,11
5  2024      Nordeste  R$ 5.184.224,85
6  2024       Sudeste  R$ 5.922.136,38
7  2024           Sul  R$ 5.878.699,91

In [363]:
# 3.2 lucro total por região
 
lucro_regiao = database.groupby(['regiao'])['lucro'].sum().reset_index().sort_values(by=['regiao'])

lucro_regiao['lucro'] = lucro_regiao['lucro'].apply(lambda x: locale.currency(x, grouping=True))

lucro_regiao

         regiao            lucro
0  Centro-Oeste  R$ 1.674.978,71
1      Nordeste  R$ 3.055.154,59
2       Sudeste  R$ 5.459.979,49
3           Sul  R$ 4.593.462,34

In [364]:
# 3.3 lucro total por região e ano
 
lucro_regiao = database.groupby(['ano','regiao'])['lucro'].sum().reset_index().sort_values(by=['ano','regiao'])

lucro_regiao['lucro'] = lucro_regiao['lucro'].apply(lambda x: locale.currency(x, grouping=True))

lucro_regiao

    ano        regiao            lucro
0  2023  Centro-Oeste    R$ 770.481,67
1  2023      Nordeste  R$ 1.598.375,82
2  2023       Sudeste  R$ 2.786.813,42
3  2023           Sul  R$ 2.256.216,48
4  2024  Centro-Oeste    R$ 904.497,04
5  2024      Nordeste  R$ 1.456.778,77
6  2024       Sudeste  R$ 2.673.166,07
7  2024           Sul  R$ 2.337.245,86

In [365]:
#faturamento por produto e ano

faturamento_produto = database.groupby(['produto_nome','ano'])['receita_liquida'].sum().reset_index().sort_values(by=['produto_nome','ano'])

faturamento_produto['receita_liquida'] = faturamento_produto['receita_liquida'].apply(lambda x: locale.currency(x, grouping=True))

faturamento_produto

             produto_nome   ano  receita_liquida
0           Cadeira Gamer  2023  R$ 2.518.465,71
1           Cadeira Gamer  2024  R$ 2.663.609,30
2           Headset Gamer  2023  R$ 2.218.490,46
3           Headset Gamer  2024  R$ 2.210.838,37
4              Mesa Gamer  2023  R$ 1.907.658,62
5              Mesa Gamer  2024  R$ 2.330.509,45
6   Microfone Condensador  2023  R$ 2.631.948,17
7   Microfone Condensador  2024  R$ 1.952.460,66
8       Monitor Ultrawide  2023  R$ 2.605.507,86
9       Monitor Ultrawide  2024  R$ 2.011.425,30
10            Mouse Gamer  2023  R$ 2.625.357,40
11            Mouse Gamer  2024  R$ 2.723.291,83
12       Teclado Mecânico  2023  R$ 2.773.141,73
13       Teclado Mecânico  2024  R$ 2.583.951,50
14              Webcam 4K  2023  R$ 2.575.087,26
15              Webcam 4K  2024  R$ 3.093.201,84

In [366]:
#faturamento por segmento

faturamento_segmento = database.groupby(['segmento_cliente','ano'])['receita_liquida'].sum().reset_index().sort_values(by=['segmento_cliente','ano'])

faturamento_segmento['receita_liquida'] = faturamento_segmento['receita_liquida'].apply(lambda x: locale.currency(x, grouping=True))

faturamento_segmento

    segmento_cliente   ano   receita_liquida
0   Consumidor Final  2023     R$ 198.641,47
1   Consumidor Final  2024     R$ 179.525,07
2        Corporativo  2023  R$ 17.731.136,79
3        Corporativo  2024  R$ 17.676.888,79
4  Pequenas Empresas  2023   R$ 1.925.878,95
5  Pequenas Empresas  2024   R$ 1.712.874,39

In [367]:
lucro_segmento = database.groupby(['segmento_cliente','ano'])['lucro'].sum().reset_index().sort_values(by=['segmento_cliente','ano'])

lucro_segmento['lucro'] = lucro_segmento['lucro'].apply(lambda x: locale.currency(x, grouping=True))

lucro_segmento

    segmento_cliente   ano            lucro
0   Consumidor Final  2023     R$ 73.934,22
1   Consumidor Final  2024     R$ 66.566,85
2        Corporativo  2023  R$ 6.614.074,62
3        Corporativo  2024  R$ 6.667.879,75
4  Pequenas Empresas  2023    R$ 723.878,55
5  Pequenas Empresas  2024    R$ 637.241,14

In [368]:
#faturamento por canal de venda

faturamento_canal_venda = database.groupby(['canal_venda','segmento_cliente'])['receita_liquida'].sum().reset_index().sort_values(by=['canal_venda'])

faturamento_canal_venda['receita_liquida'] = faturamento_canal_venda['receita_liquida'].apply(lambda x: locale.currency(x, grouping=True))

faturamento_canal_venda

   canal_venda   segmento_cliente   receita_liquida
0   E-commerce   Consumidor Final     R$ 271.766,13
1   E-commerce        Corporativo  R$ 26.605.877,19
2   E-commerce  Pequenas Empresas   R$ 2.608.384,69
3  Loja Física   Consumidor Final     R$ 106.400,41
4  Loja Física        Corporativo   R$ 8.802.148,39
5  Loja Física  Pequenas Empresas   R$ 1.030.368,65

# Análise diagnóstica

7 - Quais regiões possuem maior margem?

8 - Quais produtos geram maior lucro?

9 - Quais segmentos possuem maior potencial?

10 - Quais canais possuem melhor rentabilidade?

11 - Onde os descontos estão reduzindo margem?

12 - Existe sazonalidade?

In [369]:
#Margem por região

lucro_produto = database.groupby(['regiao'])['margem_pct'].mean().reset_index().sort_values(by=['margem_pct'], ascending=False)

lucro_produto

         regiao  margem_pct
2       Sudeste   44.968839
3           Sul   39.954286
0  Centro-Oeste   35.122933
1      Nordeste   27.925042

In [370]:
#Lucro por produto

lucro_produto = database.groupby(['produto_nome'])['lucro'].sum().reset_index().sort_values(by=['lucro'], ascending=False)

lucro_produto['lucro'] = lucro_produto['lucro'].apply(lambda x: locale.currency(x, grouping=True))

lucro_produto

            produto_nome            lucro
7              Webcam 4K  R$ 2.180.001,57
5            Mouse Gamer  R$ 2.026.066,91
6       Teclado Mecânico  R$ 1.975.306,13
0          Cadeira Gamer  R$ 1.905.779,45
4      Monitor Ultrawide  R$ 1.772.413,88
1          Headset Gamer  R$ 1.700.744,99
3  Microfone Condensador  R$ 1.656.503,59
2             Mesa Gamer  R$ 1.566.758,61

# Análise estratégica

13 - Onde devemos concentrar vendas?

14 - Quais segmentos devemos priorizar?

15 - Quais produtos devemos promover?

16 - Quais canais merecem maior investimento?

17 - Onde devemos controlar descontos?